"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 5.2.3.
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
WHATSAPP_API_URL = "https://your-node-service.onrender.com"


# --- Base Paths ---
BASE_DIR = Path(__file__).resolve().parent.parent

# # Load .env file
# dotenv_path = BASE_DIR / '.env'
# load_dotenv(dotenv_path=dotenv_path)


# --- Security Settings ---
SECRET_KEY = os.getenv("SECRET_KEY", 'django-insecure-5y#pxafeg_xf3s*zw*=rfem+faxala-3x$thv!l714e$u2js@@')
DEBUG = os.getenv("DEBUG", "True") == "True"
ALLOWED_HOSTS = ['whatsx-adavanced-automation-messaging.onrender.com']

# --- Custom User Model ---
AUTH_USER_MODEL = 'accounts.CustomUser'

# --- Installed Apps ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'messaging',

    'rest_framework',
    'rest_framework_simplejwt',

    'django_celery_beat',
    'widget_tweaks',
]

# --- Middleware ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --- URL & WSGI ---
ROOT_URLCONF = 'core.urls'
WSGI_APPLICATION = 'core.wsgi.application'

# --- Templates ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'accounts/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# --- Database ---
import dj_database_url


DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=600,
    )
}

# Optional: Add a check to fail explicitly if the DB URL is missing
if not DATABASES['default']:
    print("WARNING: DATABASE_URL environment variable is not set. This will fail on Render.")
# --- REST Framework ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# --- Password Validation ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- Static & Media ---
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# --- Localization (Timezone Fix Applied Here) ---
LANGUAGE_CODE = 'en-us'

# CORRECT TIMEZONE FOR PAKISTAN (Asia/Karachi)
TIME_ZONE = 'Asia/Karachi'

USE_I18N = True
USE_TZ = True

# --- Default Primary Key ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Fallback for login-required redirects
LOGIN_URL = '/login/'
