# Generated by Django 5.1.4 on 2025-10-09 05:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagelog',
            old_name='sent_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagelog',
            name='recipient',
        ),
        migrations.AddField(
            model_name='campaign',
            name='message_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.messagetemplate'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='message_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='recipient_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
