# Generated by Django 5.1.4 on 2025-10-09 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('messaging', '0002_rename_sent_at_messagelog_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='status',
            field=models.CharField(default='completed', max_length=20),
        ),
        migrations.CreateModel(
            name='MessageCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message_content', models.TextField(default='', help_text='The final message content to send.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending (Scheduled)'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('total_recipients', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_failed', models.IntegerField(default=0)),
                ('message_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.messagetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='messaging.messagecampaign'),
        ),
        migrations.CreateModel(
            name='WhatsAppCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('phone_number_id', models.CharField(blank=True, max_length=100, null=True)),
                ('business_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='The actual phone number used.', max_length=20)),
                ('send_status', models.CharField(choices=[('PENDING', 'Pending Send'), ('SENT', 'Sent Successfully'), ('FAILED', 'Failed to Send'), ('SKIPPED', 'Skipped (e.g., invalid number)')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contact')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='messaging.messagecampaign')),
            ],
            options={
                'unique_together': {('campaign', 'phone_number')},
            },
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
