# Generated by Django 5.1.4 on 2025-10-09 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_messagelog_status_messagecampaign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappcredentials',
            options={'verbose_name_plural': 'WhatsApp Credentials'},
        ),
        migrations.RemoveField(
            model_name='whatsappcredentials',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='whatsappcredentials',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='whatsappcredentials',
            name='id',
        ),
        migrations.RemoveField(
            model_name='whatsappcredentials',
            name='phone_number_id',
        ),
        migrations.AddField(
            model_name='whatsappcredentials',
            name='session_id',
            field=models.CharField(blank=True, help_text='ID used by the Node.js server for session persistence.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappcredentials',
            name='status',
            field=models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('QR_READY', 'QR Ready'), ('LOGGING_IN', 'Logging In')], default='DISCONNECTED', help_text='Current connection status with WhatsApp API.', max_length=50),
        ),
        migrations.AddField(
            model_name='whatsappcredentials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='whatsappcredentials',
            name='whatsapp_phone_number',
            field=models.CharField(blank=True, help_text='The phone number associated with the connected WhatsApp account.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappcredentials',
            name='user',
            field=models.OneToOneField(help_text='The Django user this connection belongs to.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='whatsappcredentials', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
