# Generated by Django 5.1.4 on 2025-10-11 08:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('messaging', '0004_alter_whatsappcredentials_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignrecipient',
            options={'ordering': ['send_status', 'phone_number']},
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 11, 8, 31, 5, 580242, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Optional link to Contact list.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contact'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='messaging.messagecampaign'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='status',
            field=models.CharField(default='sent', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='dailyquota',
            unique_together={('user', 'date')},
        ),
    ]
