# Generated by Django 5.1.4 on 2025-10-14 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('messaging', '0005_alter_campaignrecipient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagecampaign',
            name='message_template',
        ),
        migrations.RemoveField(
            model_name='messagecampaign',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messagelog',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='whatsappcredentials',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='campaignrecipient',
            options={'ordering': ['-campaign__created_at', 'phone_number']},
        ),
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='campaignrecipient',
            name='send_status',
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together={('title', 'created_by')},
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contact'),
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='phone_number',
            field=models.CharField(help_text='The E.164 formatted phone number.', max_length=20),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='content',
            field=models.TextField(help_text='The body of the message. You can use placeholders like {{name}}.'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='title',
            field=models.CharField(help_text='A unique name for this template for easy identification.', max_length=200),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the campaign for tracking purposes.', max_length=255)),
                ('message_content', models.TextField(help_text='The final message body that will be sent to all recipients.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Schedule'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='If set, the campaign will start at this time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='messaging.campaign'),
        ),
        migrations.DeleteModel(
            name='DailyQuota',
        ),
        migrations.DeleteModel(
            name='MessageLog',
        ),
        migrations.DeleteModel(
            name='WhatsAppCredentials',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='image',
        ),
        migrations.DeleteModel(
            name='MessageCampaign',
        ),
    ]
