# Generated by Django 5.1.4 on 2025-10-20 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_remove_messagecampaign_message_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={},
        ),
        migrations.AlterModelOptions(
            name='campaignrecipient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='campaignrecipient',
            name='contact',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='message_content',
            field=models.TextField(help_text='The final message that will be sent.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(help_text='The name of the campaign for tracking.', max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Schedule'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='content',
            field=models.TextField(help_text='The message body. Use {{name}} for placeholders.'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='title',
            field=models.CharField(help_text='A name for this template.', max_length=200),
        ),
    ]
