# Generated by Django 5.1.4 on 2025-10-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_alter_campaign_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='campaign',
            name='document_attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/documents/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='image_attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/images/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='video_attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/videos/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='message_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
