# Generated by Django 5.1.4 on 2025-10-25 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_alter_campaignrecipient_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='document_attachment',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='image_attachment',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='video_attachment',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.campaign')),
            ],
        ),
    ]
